name: astronomy_picture
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  equatable: ^2.0.5
  mockito: ^5.4.0
  get_it: ^7.3.0
  video_player: ^2.6.1
  youtube_player_flutter: ^8.1.2
  vimeo_video_player: ^0.0.9
  url_launcher: ^6.1.10
  flutter_local_notifications: ^14.0.0+1
  timezone: ^0.9.2
  flutter_native_timezone: ^2.0.0
  syncfusion_flutter_datepicker: ^21.2.3
  shared_preferences: ^2.1.0
  gallery_saver: ^2.3.2
  share_plus: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/icon.png