// Mocks generated by Mockito 5.4.0 from annotations
// in astronomy_picture/test/data/repositories/bookmark_apod/bookmark_apod_repository_impl.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astronomy_picture/core/success_return.dart' as _i2;
import 'package:astronomy_picture/data/datasources/bookmark_apod/bookmark_apod_data_source.dart'
    as _i3;
import 'package:astronomy_picture/data/models/apod_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSuccessReturn_0 extends _i1.SmartFake implements _i2.SuccessReturn {
  _FakeSuccessReturn_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookmarkApodDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookmarkApodDataSource extends _i1.Mock
    implements _i3.BookmarkApodDataSource {
  @override
  _i4.Future<_i2.SuccessReturn> saveApod(_i5.ApodModel? apod) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveApod,
          [apod],
        ),
        returnValue: _i4.Future<_i2.SuccessReturn>.value(_FakeSuccessReturn_0(
          this,
          Invocation.method(
            #saveApod,
            [apod],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.SuccessReturn>.value(_FakeSuccessReturn_0(
          this,
          Invocation.method(
            #saveApod,
            [apod],
          ),
        )),
      ) as _i4.Future<_i2.SuccessReturn>);
  @override
  _i4.Future<_i2.SuccessReturn> removeSaveApod(String? apodDate) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeSaveApod,
          [apodDate],
        ),
        returnValue: _i4.Future<_i2.SuccessReturn>.value(_FakeSuccessReturn_0(
          this,
          Invocation.method(
            #removeSaveApod,
            [apodDate],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.SuccessReturn>.value(_FakeSuccessReturn_0(
          this,
          Invocation.method(
            #removeSaveApod,
            [apodDate],
          ),
        )),
      ) as _i4.Future<_i2.SuccessReturn>);
  @override
  _i4.Future<bool> apodIsSave(String? apodDate) => (super.noSuchMethod(
        Invocation.method(
          #apodIsSave,
          [apodDate],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  _i4.Future<List<_i5.ApodModel>> getAllApodSave() => (super.noSuchMethod(
        Invocation.method(
          #getAllApodSave,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ApodModel>>.value(<_i5.ApodModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.ApodModel>>.value(<_i5.ApodModel>[]),
      ) as _i4.Future<List<_i5.ApodModel>>);
}
