// Mocks generated by Mockito 5.4.0 from annotations
// in astronomy_picture/test/presentation/search/search_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astronomy_picture/core/failure.dart' as _i5;
import 'package:astronomy_picture/domain/entities/apod.dart' as _i9;
import 'package:astronomy_picture/domain/usecases/core/usecase.dart' as _i6;
import 'package:astronomy_picture/domain/usecases/search/fetch_search_history.dart'
    as _i3;
import 'package:astronomy_picture/domain/usecases/search/get_apod_by_date_range.dart'
    as _i8;
import 'package:astronomy_picture/domain/usecases/search/update_search_history.dart'
    as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchSearchHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchSearchHistory extends _i1.Mock
    implements _i3.FetchSearchHistory {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> call(
          _i6.NoParameter? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}

/// A class which mocks [UpdateSearchHistory].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateSearchHistory extends _i1.Mock
    implements _i7.UpdateSearchHistory {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> call(
          List<String>? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}

/// A class which mocks [GetApodByDateRange].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetApodByDateRange extends _i1.Mock
    implements _i8.GetApodByDateRange {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Apod>>> call(String? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i9.Apod>>>.value(
            _FakeEither_0<_i5.Failure, List<_i9.Apod>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i9.Apod>>>.value(
                _FakeEither_0<_i5.Failure, List<_i9.Apod>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Apod>>>);
}
