// Mocks generated by Mockito 5.4.0 from annotations
// in astronomy_picture/test/presentation/bookmark_apod/bookmark_apod_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astronomy_picture/core/failure.dart' as _i5;
import 'package:astronomy_picture/core/success_return.dart' as _i10;
import 'package:astronomy_picture/domain/entities/apod.dart' as _i7;
import 'package:astronomy_picture/domain/usecases/bookmark_apod/apod_is_save.dart'
    as _i3;
import 'package:astronomy_picture/domain/usecases/bookmark_apod/get_all_apod_save.dart'
    as _i6;
import 'package:astronomy_picture/domain/usecases/bookmark_apod/remove_save_apod.dart'
    as _i9;
import 'package:astronomy_picture/domain/usecases/bookmark_apod/save_apod.dart'
    as _i11;
import 'package:astronomy_picture/domain/usecases/core/usecase.dart' as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApodIsSave].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodIsSave extends _i1.Mock implements _i3.ApodIsSave {
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> call(String? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [GetAllApodSave].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllApodSave extends _i1.Mock implements _i6.GetAllApodSave {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.Apod>>> call(
          _i8.NoParameter? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i7.Apod>>>.value(
            _FakeEither_0<_i5.Failure, List<_i7.Apod>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.Apod>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.Apod>>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.Apod>>>);
}

/// A class which mocks [RemoveSaveApod].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveSaveApod extends _i1.Mock implements _i9.RemoveSaveApod {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>> call(
          String? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>>.value(
                _FakeEither_0<_i5.Failure, _i10.SuccessReturn>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>>.value(
                _FakeEither_0<_i5.Failure, _i10.SuccessReturn>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>>);
}

/// A class which mocks [SaveApod].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveApod extends _i1.Mock implements _i11.SaveApod {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>> call(
          _i7.Apod? parameter) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [parameter],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>>.value(
                _FakeEither_0<_i5.Failure, _i10.SuccessReturn>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>>.value(
                _FakeEither_0<_i5.Failure, _i10.SuccessReturn>(
          this,
          Invocation.method(
            #call,
            [parameter],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i10.SuccessReturn>>);
}
